server:
  port: 8081
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: shopping_cart_service_route
          uri: lb:/SHOPPING-CART

          predicates:
            - Path=/shopping-cart/**
          filters:
            - PrefixPath=/api/v1
